# Script to perform Vst analysis on GEO data generated by Towfique Raj et al.

importExp <- function(cell) {
	exp.list <- list()
	for (pop in c('Caucasian','African-American','Asian')) {
		load(file=paste('exp_genes',cell,pop,'Robj',sep='.'))
		exp.list <- unlist(list(exp.list, list(exp_genes)), recursive=FALSE)
	}
	return(exp.list)
}

calculateVst <- function(pop1.exp, pop2.exp) {

	n1 <- length(pop1.exp)
	n2 <- length(pop2.exp)
	v1 <- var(pop1.exp)
	v2 <- var(pop2.exp)
	Vs <- (v1*n1 + v2*n2)/(n1+n2)

	Vt <- var(c(pop1.exp, pop2.exp))
	Vst <- (Vt - Vs)/Vt
	return(Vst)
}

pairwiseVst <- function(exp1, exp2) {
	x <- numeric()
	shared.genes <- intersect(rownames(exp1), rownames(exp2))
	for (gene in shared.genes) {
		x <- c(x,calculateVst(na.omit(exp1[gene, ]), na.omit(exp2[gene, ])))
	}
	names(x) <- shared.genes
	return(x)
}

library(oligo)
library(GEOquery)

setwd('/group/stranger-lab/immvar_data/')

############# CD14 Data
load('/group/stranger-lab/immvar_rep/GSE56034.Robj')
cd14.eset <- exprs(gse56034[[1]])
cd14.pdat <- pData(gse56034[[1]]) # Population not given. Must overlap with phen

EU_PC.cd14 <- as.matrix(read.table(file='/group/stranger-lab/immvar_rep/GSE56034_GSM.ImmVarCD14.EU.PC20.txt', header=T, row.names=1))
EA_PC.cd14 <- as.matrix(read.table(file='/group/stranger-lab/immvar_rep/GSE56034_GSM.ImmVarCD14.EA.PC10.txt', header=T, row.names=1))
AA_PC.cd14 <- as.matrix(read.table(file='/group/stranger-lab/immvar_rep/GSE56034_GSM.ImmVarCD14.AA.PC14.txt', header=T, row.names=1))

cau_ids.cd14 <- colnames(EU_PC.cd14)
asn_ids.cd14 <- colnames(EA_PC.cd14)
afr_ids.cd14 <- colnames(AA_PC.cd14)

############## CD4 Data
load('/group/stranger-lab/immvar_rep/GSE56033.Robj')
cd4.eset <- exprs(gse56033[[1]])
cd4.pdat <- pData(gse56033[[1]])

EU_PC.cd4 <- as.matrix(read.table(file='/group/stranger-lab/immvar_rep/GSE56033_GSM.ImmVarCD4.EU.PC20.txt', header=T, row.names=1))
AA_PC.cd4 <- as.matrix(read.table(file='/group/stranger-lab/immvar_rep/GSE56033_GSM.ImmVarCD4.AA.PC12.txt', header=T, row.names=1))
EA_PC.cd4 <- as.matrix(read.table(file='/group/stranger-lab/immvar_rep/GSE56033_GSM.ImmVarCD4.EA.PC12.txt', header=T, row.names=1))

cau_ids.cd4 <- colnames(EU_PC.cd4)
asn_ids.cd4 <- colnames(EA_PC.cd4)
afr_ids.cd4 <- colnames(AA_PC.cd4)

load('/group/stranger-lab/moliva/ImmVar/Robjects/phen.Robj')
load('/group/stranger-lab/moliva/ImmVar/probes_mapping/Robjects/merge_probes_DF.Robj')

phen.cd14 <<- phen[phen$PhenotypeMarkers=="CD3- CD14+ CD16-",]
phen.cd4 <- phen[phen$PhenotypeMarkers=="CD3+ CD14- CD8- CD4+ CD62L+ CD25-", ]

cd14.pops <- list(cau_ids.cd14, afr_ids.cd14, asn_ids.cd14)
cd4.pops <- list(cau_ids.cd4, afr_ids.cd4, asn_ids.cd4)

if (!file.exists('/group/stranger-lab/czysz/ImmVar/norm.cd14.vst.towfique.Robj')) {
cd14.vst.list <- list()
pops <- c('Caucasian', 'African-American', 'Asian')
for (i in seq(2)) {
for (j in (i+1):3) {
	eset <- cd14.eset[, colnames(cd14.eset)%in%cd14.pops[[i]]]
	norm_eset <- apply(eset, 1, function(x) { x / mean(x) })
	eset_i <- t(norm_eset)
	
	eset <- cd14.eset[, colnames(cd14.eset)%in%cd14.pops[[j]]]
	norm_eset <- apply(eset, 1, function(x) { x / mean(x) })
	eset_j <- t(norm_eset)
	vst <- pairwiseVst(eset_i, eset_j)
	cd14.vst.list <- unlist(list(cd14.vst.list, list(vst)), recursive=FALSE)
	} } 
	save(cd14.vst.list,file='/group/stranger-lab/czysz/ImmVar/norm.cd14.vst.towfique.Robj')
} else load('/group/stranger-lab/czysz/ImmVar/norm.cd14.vst.towfique.Robj')

if (!file.exists('/group/stranger-lab/czysz/ImmVar/cd4.vst.towfique.Robj')) {
cd4.vst.list <- list()
for (i in seq(2)) {
for (j in (i+1):3) {
	vst <- pairwiseVst(cd4.eset[, colnames(cd4.eset)%in%cd4.pops[[i]]], cd4.eset[, colnames(cd4.eset)%in%cd4.pops[[j]]])
	cd4.vst.list <- unlist(list(cd4.vst.list, list(vst)), recursive=FALSE)
	} } 
	save(cd4.vst.list,file='/group/stranger-lab/czysz/ImmVar/cd4.vst.towfique.Robj')
} else load('/group/stranger-lab/czysz/ImmVar/cd4.vst.towfique.Robj')

#shared.genes <- intersect(intersect(names(cd14.vst.list[[1]]), names(cd14.vst.list[[2]])), names(cd14.vst.list[[3]]))

#for (i in seq(3)) { cd14.vst.list[[i]] <- cd14.vst.list[[i]][shared.genes] }

top.diff.genes <- c()
for ( i in seq(3)) {
	top.diff <- cd14.vst.list[[i]][cd14.vst.list[[i]] > quantile(cd14.vst.list[[i]], probs=c(0.99),na.rm=T)]
	top.diff.genes <- c(top.diff.genes, names(top.diff))	
}

annot <- read.table(file='/group/stranger-lab/moliva/ImmVar/probes_mapping/annotations/gencode.v22.TSS.txt',header=T,row.names=1,as.is=T)

cd14.rep <- c("UTS2","FLNB","SPTBN1","SMAGP","EMP1","TTC39C","PSPH","SPATA20","PPIL3","F2RL1","LRRC6","RFX2","LMNA","P2RX5","PRH1","SIGLEC14","GATM","LILRA3")

cd14.rep_geneid <- unique(merge_probes_DF[merge_probes_DF$gene_symbols%in%cd14.rep,"transcript_cluster_id"])

cd14.all <- cbind(cd14.vst.list[[1]][names(cd14.vst.list[[1]])%in%cd14.rep_geneid],
	cd14.vst.list[[2]][names(cd14.vst.list[[2]])%in%cd14.rep_geneid],
	cd14.vst.list[[3]][names(cd14.vst.list[[3]])%in%cd14.rep_geneid])
colnames(cd14.all) <- c("EU-AA","EU-EA","AA-EA")

cd4.rep <- c("UTS2","CRIP2","NR1D1","C11orf21","VIM","TRPM2","TMEM14C","RPL36AL","PTCH1","PSPH","HOXB2","HEBP2","GPR137B","AFAP1","CCDC144A","FHIT","PPFIBP2","GSTM4")

cd4.rep_geneid <- unique(merge_probes_DF[merge_probes_DF$gene_symbols%in%cd4.rep,"transcript_cluster_id"])

cd4.all <- cbind(cd4.vst.list[[1]][names(cd4.vst.list[[1]])%in%cd4.rep_geneid],
	cd4.vst.list[[2]][names(cd4.vst.list[[2]])%in%cd4.rep_geneid],
	cd4.vst.list[[3]][names(cd4.vst.list[[3]])%in%cd4.rep_geneid])
colnames(cd4.all) <- c("EU-AA","EU-EA","AA-EA")

if (F) {
pdf(file='/group/stranger-lab/czysz/ImmVar/plots/cd14.towfique.vst.pdf')
boxplot(cd14.vst.list[[1]], cd14.vst.list[[2]], cd14.vst.list[[3]], names=c('EU-AA','EU-EA','AA-EA'),main="CD14 Vst scores. Towfique Data")
dev.off()

pdf(file='/group/stranger-lab/czysz/ImmVar/plots/cd14.towfique.vst.trunc.pdf')
boxplot(cd14.vst.list[[1]][cd14.vst.list[[1]]<0.1], cd14.vst.list[[2]][cd14.vst.list[[2]]<0.1], cd14.vst.list[[3]][cd14.vst.list[[3]]<0.1], names=c('EU-AA','EU-EA','AA-EA'),main="Truncated CD14 Vst scores. Towfique Data")
dev.off()

pdf(file='/group/stranger-lab/czysz/ImmVar/plots/cd4.towfique.vst.pdf')
boxplot(cd4.vst.list[[1]], cd4.vst.list[[2]], cd4.vst.list[[3]], names=c('EU-AA','EU-EA','AA-EA'),main="CD4 Vst scores. Towfique Data")
dev.off()

pdf(file='/group/stranger-lab/czysz/ImmVar/plots/cd4.towfique.vst.trunc.pdf')
boxplot(cd4.vst.list[[1]][cd4.vst.list[[1]]<0.1], cd4.vst.list[[2]][cd4.vst.list[[2]]<0.1], cd4.vst.list[[3]][cd4.vst.list[[3]]<0.1], names=c('EU-AA','EU-EA','AA-EA'),main="Truncated CD4 Vst scores. Towfique Data")
dev.off()
}
pops <- c('EU','AA','EA')
cd14.pcs <- list(EU_PC.cd14, AA_PC.cd14, EA_PC.cd14)
cd4.pcs <- list(EU_PC.cd4, AA_PC.cd4, EA_PC.cd4)
pdf(file='/group/stranger-lab/czysz/ImmVar/plots/towfique.exp.pdf')
for (i in seq(3)) {
	plot(density(na.omit(as.numeric(cd14.eset[,colnames(cd14.eset)%in%colnames(cd14.pcs[[i]])]))),col='red',main=pops[i])
	lines(density(na.omit(as.numeric(cd4.eset[,colnames(cd4.eset)%in%colnames(cd4.pcs[[i]])]))),col='blue')
}
dev.off()

pdf(file='/home/t.cri.cczysz/rep.cd14.plots.pdf')
for (gene in cd14.rep_geneid) {
	tot_exp <- cd14.eset[as.character(gene),]
	cau_exp <- as.numeric(na.omit(tot_exp[names(tot_exp)%in%cau_ids.cd14]))
	afr_exp <- as.numeric(na.omit(tot_exp[names(tot_exp)%in%afr_ids.cd14]))
	asn_exp <- as.numeric(na.omit(tot_exp[names(tot_exp)%in%asn_ids.cd14]))

	plot(density(as.numeric(na.omit(tot_exp))), main=paste(gene, 'Total Expression'), col='black')
	plot(density(cau_exp), main=paste(gene, 'Pop\'n specific expression'),col='red')
	lines(density(afr_exp), col='blue')
	lines(density(asn_exp), col='black')
}
dev.off()

pdf(file='/home/t.cri.cczysz/rep.cd4.plots.pdf')
for (gene in cd4.rep_geneid) {
	tot_exp <- cd4.eset[as.character(gene),]
	cau_exp <- as.numeric(na.omit(tot_exp[names(tot_exp)%in%cau_ids.cd4]))
	afr_exp <- as.numeric(na.omit(tot_exp[names(tot_exp)%in%afr_ids.cd4]))
	asn_exp <- as.numeric(na.omit(tot_exp[names(tot_exp)%in%asn_ids.cd4]))

	plot(density(as.numeric(na.omit(tot_exp))), main=paste(gene, 'Total Expression'), col='black')
	plot(density(cau_exp), main=paste(gene, 'Pop\'n specific expression'), col='red')
	lines(density(afr_exp), col='blue')
	lines(density(asn_exp), col='black')
}
dev.off()
